language: node_js

sudo: required

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - node_js: "6"
      env: TEST_TARGET=docker
      services: docker
    - node_js: "6"
      env: TEST_TARGET=node
    - node_js: "7"
      env: TEST_TARGET=node

install:
  - if [ "$TEST_TARGET" == "node" ]; then npm install -g yarn; yarn install; else echo "skipped"; fi
  - if [ "$TEST_TARGET" == "docker" ]; then docker build -t="404busters/builder" .; else echo "skipped"; fi

script:
  - if [ "$TEST_TARGET" == "node" ]; then yarn build; else echo "skipped"; fi
  - if [ "$TEST_TARGET" == "docker" ]; then docker run --name builder -it --rm -v $PWD/public:/app/public 404busters/builder; else echo "skipped"; fi
